# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Linting, formatting & spellcheck
          command: |
            yarn check:lint --format junit -o reports/junit/js-lint-results.xml
            yarn check:format
            yarn check:spelling

      - run:
          name: Security audit
          command: yarn audit --level moderate

      - run:
          name: Unit & integration tests
          command: yarn test:coverage --ci --runInBand --reporters=default --reporters=jest-junit && npx codecov
          environment:
            JEST_SUITE_NAME: 'Unit & integration tests'
            JEST_JUNIT_OUTPUT_DIR: './reports/junit/'
            JEST_JUNIT_OUTPUT_NAME: 'js-test-results.xml'

      - run:
          name: End-to-end tests
          command: yarn test:e2e --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_SUITE_NAME: 'End-to-end tests'
            JEST_JUNIT_OUTPUT_DIR: './reports/junit/'
            JEST_JUNIT_OUTPUT_NAME: 'js-e2e-test-results.xml'

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit
